### ISSUE TITLE
Derelcit Structure Anomaly

### ISSUE THREAD

**Issue by nCrazed** [MoreEventsMod/More_Events_Mod_Beta#163]
Based on @tcarrell's idea in #128
- [x] Derelict structures on asteroid. Might find any of the following:
  - [x] ![Expertise: Minerals](http://www.stellariswiki.com/images/f/f4/Materials.png) Purpose unknown, could salvage a few minerals +minerals
  - [x] ![Expertise: Industry](http://www.stellariswiki.com/images/1/13/Industry.png)  Purpose unknown, large functional power source, +energy generation on asteroid
  - [x] ![Expertise: Voidcraft](http://www.stellariswiki.com/images/b/b9/Voidcraft.png)  Purpose unknown, interesting composition +engineering tech
  - [x] ![Expertise: Field Manipulation](http://www.stellariswiki.com/images/8/84/Field_Manipulation.png) Small warp loop (think pendulum but with short range ftl), novel, predicted to sustain for 2.6 billion years, +physics
  - [x] ![Expertise: Particles](http://www.stellariswiki.com/images/c/c1/Particles.png) Strange warp tech, not enough survived to understand full purpose, but could give theoretical insights, +physics generation
  - [x] ![Expertise: Biology](http://www.stellariswiki.com/images/4/46/Biology.png) Structures wrecked beyond salvage our understanding, but some biological matter left behind fascinated our xenobiologist, +society tech generation on asteroid

The outcomes should be weighted based on relevant Expertise traits of the researcher.

So for example if the leader that discovered this anomaly has the ![Expertise: Biology](http://www.stellariswiki.com/images/4/46/Biology.png) `Expertise: Biology` trait then there should be a higher chance of +society yield.
### TODO
- [x] Decide on balance for the anomaly level, risk and rewards.
- [x] Finish the writing.
- [x] Test trait influence on category chance.

**Comment by nCrazed** [comment]
Any suggestions for the +physics yield traits?

**Comment by tzerrell** [comment]
I like field manipulation for the loop and particles for the "not enough survived" one, but I don't feel super strongly about these; in particular not enough survived could be pretty much anything.

Could also wait and see how the writing comes out.

**Comment by nCrazed** [comment]
Did some testing for the outcomes of the different categories as "United Nations of Earth" with default settings by running 18 anomalies of each category. From what I can tell, each category applied its weights correctly.

Not sure how to test that the traits of the scientist influence the anomaly category correctly; testing it manually seems infeasible.

**Comment by tzerrell** [comment]
2 options occur to me:
- Just trust that it's working
- Temporarily change the code so that traits have a massive impact (make one category 100 times more likely or something); test that you basically always get the corresponding category

**Comment by nCrazed** [comment]
The problem with that approach is that you're still fighting against the chance of discovering any anomaly which appears to be very low. The start settings that I used always have 4 asteroids and most of the runs I get 0 natural anomaly occurrences on them.

Is there a way to make the general anomaly rate significantly higher?

**Comment by tzerrell** [comment]
Ah. That I don't know how to do :/

But if you make the weight factor high enough (x10000 maybe?) you have a very high chance of getting this category for any anomaly on an asteroid, so you only have to run it a few times. Not ideal, but not completely unreasonable either

**Comment by nCrazed** [comment]
And I should not forget to make the categories visibly different in-game. Just got one hit, but no way of telling which category it was :D

**Comment by tzerrell** [comment]
haha, oops

**Comment by nCrazed** [comment]
Anyone testing this will want to create `common/defines/anonaly_testing.lua` file with the following content:

``` lua
NDefines.NGameplay.ANOMALY_SPAWN_CHANCE = 1
```

You might also want to tweak the values of `@risk` and `@biased_modifier` in `common/anomalies/mem_asteroid_derelict_structure_anomaly_category.txt` as well as the different category title strings in the localization files to be able to distinguish the categories in-game.

**Comment by Deytron** [comment]
Confirmed working, got the biology end, one issue though : 
- The scientific name for the first popup isn't appearing, must be wrong alias used

**Comment by nCrazed** [comment]
At this point I am starting to thin that it's impossible to reference the leader's name from an anomaly **category** event.

**Comment by tzerrell** [comment]
Oh whoops, I'd completely forgotten, but that is definitely true. You can't reference the leader, ship, or empire from the anomaly category.

**Comment by Hoeya** [comment]
Initial writing for anomaly event has been completed and pushed to **dev.** Let me know if there's any concerns, issues, etc.

**Comment by nCrazed** [comment]
I've got almost no interest until tomorrow. Once that's resolved I'll take a look at it.

**Comment by nCrazed** [comment]
That was supposed to be internet, not interest :|

**Comment by nCrazed** [comment]
Since this was released I am assuming that reward values are acceptable.
