### ISSUE TITLE
2.0 Proofreading Check

### ISSUE THREAD

**Issue by Tuttu** [MoreEventsMod/More_Events_Mod_Beta#352]
- [x] **Premature Ageing** (In Dev branch) : This one should be quick as a first proofreading had been done by @tzerrell. There's only a few new lines to check. You can refer to issue #255 for more informations.
- [x] **Stuck in glacier** (Currently in glacier branch) #278 
- [x] **Borehole** (Currently in borehole branch) #277
- [x] **Food Constructor** (Text is finished, although it still awaits ships. Currently in food_constructor branch) #235 contains most on the plot, however some expansion was done regarding events to handle better
- [x] **Visitor** (Currently in visitor branch.  #287 although events were added. Ophidian is no longer on the case.
- [x] **Hi There** (Currently in hithere branch. Text is likely complete, although some extra content might be added later) 
- [ ] **Death World** (Currently in death_world branch. Unlikely to change, but might) #274 Hive Mind branch is not reflected in the issue
- [x] **Rogue drone** (Likely finished, although text might require flavor and lore friendly-revision. I am not in condition to review other people's text) 
- [x] **The Last Orila** (in "last_orila" branch; loc file is complete but could need some rephrasing maybe)
- [ ] **The Maze** (in _maze_ branch) Unlikely to expand but country modifiers might turn into edicts which would add descriptions. Could use better descriptions of special projects, those suck.
- [x] **Under Blanket** (in Dev branch) Text is complete. #318 for reference.
- [x] **Primitives event** (In _primitives_ branch) Some plans ended up unfulfilled, but I think I'm out of inspiration for now, but please do warn me if you start changing files.
Please add more you features as you have completed then.
- [ ] **Synthetic sun** (In _synthetic_sun_ branch) - probably done. May add another outcome later, but it's redundant, 5 is more than enough.
- [x] **Pioneer** - (in pioneer branch) - Proofread and check please, otherwise it should be done. #238 for reference.
- [x] **Left for Dead** - (in left-for-dead branch) - Proofread and test please, working normally, just routine checks please. #222 for reference.
- [x] **Nanobot Room** - (in nanobot-room branch) - Check writing, make adjustments if necessary. Needs proofreading and testing but should be done. Small part of #128.
- [x] **Lunar age** - (in _lunar_era_ branch) Needs stylistic help. No corresponding issue 
- [x] **Legacy of the Carcharorion** (in _lotc_ branch) - Extensive event chain. Mostly present in #284 although I think I added some events for better flow.
